import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import AdminLayout from '../../components/admin/AdminLayout'
import { useToast } from '../../contexts/ToastContext'
import { getCurrentSession } from '../../lib/auth'
import { getAuditLogs, type AuditLog } from '../../lib/audit'
import { getFriendlyErrorMessage } from '../../lib/errors'
import { requireAdmin } from '../../lib/roles'

export default function AdminAuditPage() {
  const navigate = useNavigate(); const toast = useToast(); const [logs, setLogs] = useState<AuditLog[]>([]); const [search, setSearch] = useState(''); const [action, setAction] = useState('all'); const [target, setTarget] = useState('all'); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [detail, setDetail] = useState<AuditLog | null>(null)
  useEffect(() => { void (async () => { if (!(await getCurrentSession())) return navigate('/admin/login', { replace: true }); await requireAdmin(); setLogs(await getAuditLogs()) })().catch((error) => { toast.error(getFriendlyErrorMessage(error)); navigate('/admin/login', { replace: true }) }) }, [navigate, toast])
  const actions = [...new Set(logs.map((log) => log.action))]; const targets = [...new Set(logs.map((log) => log.target_type))]
  const visible = useMemo(() => logs.filter((log) => { const text = `${log.actor_email ?? ''} ${log.action} ${log.target_label ?? ''}`.toLowerCase(); const date = log.created_at.slice(0, 10); return (!search || text.includes(search.toLowerCase())) && (action === 'all' || log.action === action) && (target === 'all' || log.target_type === target) && (!start || date >= start) && (!end || date <= end) }), [action, end, logs, search, start, target])
  return <AdminLayout title="Auditoria" subtitle="Histórico das alterações administrativas."><div className="admin-card"><div className="audit-filters"><label>Busca<input type="search" value={search} onChange={(event) => setSearch(event.target.value)} /></label><label>Ação<select value={action} onChange={(event) => setAction(event.target.value)}><option value="all">Todas</option>{actions.map((item) => <option key={item}>{item}</option>)}</select></label><label>Alvo<select value={target} onChange={(event) => setTarget(event.target.value)}><option value="all">Todos</option>{targets.map((item) => <option key={item}>{item}</option>)}</select></label><label>De<input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>Até<input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></label></div><div className="governance-list">{visible.map((log) => <article className="governance-row audit-row" key={log.id}><time>{new Date(log.created_at).toLocaleString('pt-BR')}</time><span>{log.actor_email || 'Sistema'}</span><strong>{log.action}</strong><span>{log.target_label || log.target_id || log.target_type}</span><button className="secondary-button compact-button" type="button" onClick={() => setDetail(log)}>Ver detalhes</button></article>)}</div></div>{detail ? <div className="confirmation-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setDetail(null) }}><section className="confirmation-modal audit-detail" role="dialog" aria-modal="true" aria-labelledby="audit-title"><h2 id="audit-title">Detalhes da auditoria</h2><pre>{JSON.stringify(detail, null, 2)}</pre><div className="confirmation-actions"><button className="secondary-button" type="button" onClick={() => setDetail(null)}>Fechar</button></div></section></div> : null}</AdminLayout>
}
